# Generated by Django 3.0.2 on 2020-01-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0004_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='grand_total',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
