# Generated by Django 3.0.2 on 2020-01-15 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0005_cart_grand_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='grand_total',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
