# Generated by Django 3.0.2 on 2020-01-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0009_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='grand_total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
