# Generated by Django 3.0.2 on 2020-01-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0011_auto_20200122_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
