# Generated by Django 3.0.2 on 2020-01-23 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0012_auto_20200122_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='amount',
        ),
    ]
