# Generated by Django 3.0.2 on 2020-01-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0020_order_grandtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='grandTotal',
        ),
        migrations.AddField(
            model_name='cart',
            name='grandTotal',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
