# Generated by Django 3.0.2 on 2020-01-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0022_auto_20200128_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='grandTotal',
            field=models.FloatField(default=0),
        ),
    ]
