# Generated by Django 3.0.2 on 2020-01-30 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0029_auto_20200129_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
